### ISSUE TITLE
Can't refresh tokens when access token is expired

### ISSUE THREAD

**Issue by tedraykov** [reactioncommerce/plugin-authentication#43]
In order to refresh an expired access token, the accounts js schema provides the `refreshTokens` mutation. The problem is that before the request for refreshing the auth token can be executed by accountsjs, the flow goes through a middleware that gets the user for the session if the authorization header is present:

- https://github.com/reactioncommerce/api-plugin-authentication/blob/9ed06878ab0504b8097e3ae97b9a373a8b6d2931/src/util/tokenMiddleware.js#L28

From the client-side there is no easy way to make `refreshTokens` request without adding the `Authorization` header (The accountsjs client automatically adds the header) and the solution to this problem is to introduce a change in the authentication plugin.

Currently, we have the following scenario:
When we have an expired access token and a valid refresh token, we make a `refreshTokens` request.
The expired access token is added to the headers non the less

![image](https://user-images.githubusercontent.com/32718995/149988037-d234fdf9-1074-4268-bcd3-7de2f22ca38d.png)

The refreshing fails because the request fails even before it had reached the accountsjs logic for refreshing.
The correct workflow should be as follows:

![image](https://user-images.githubusercontent.com/32718995/149988083-49b428de-ce08-4f82-a5c2-249727399c96.png)

If the provided Authorization header is expired, proceed with the execution of the code as if no header was added. In other words, it should skip the provided token in the `Authorization` header before it tries to get the user session.

**Comment by tedraykov** [comment]
The solution I had in mind looks like this:

The `getUserFromAuthToken` function should be:
```javascript
async function getUserFromAuthToken(loginToken) {
  const { accountsServer } = await getAccounts();
  const authToken = loginToken.replace(/bearer\s/gi, "");

  if (hasTokenExpired(authToken)) return null;

  return accountsServer.resumeSession(authToken);
}
```

The token expiration can be done with an npm package `jwt-decode`:
```javascript
import jwtDecode from "jwt-decode";

/**
 * @summary Check if jwt token has expired
 * @name hasTokenExpired
 * @param {string} authToken - the encoded JWT
 * @returns {boolean} whether the token has expired
 */
export default function hasTokenExpired(authToken) {
  const currentTime = Date.now() / 1000;
  const decodedToken = jwtDecode(authToken);
  return decodedToken.exp < currentTime;
}
```

**Comment by Akarshit** [comment]
This looks like a viable solution to me.
